openapi: 3.0.3
info:
  title: Usertask Management API
  version: 1.0.0
  description: Usertask Management Service APIs for managing usertasks.
  contact:
    name: Cristiano Dias
  license:
    name: Apache 2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: http://localhost:8081
  
    description: Generated server url
tags:
  - name: producer-controller
    description: Producer Controller
paths:
  /usertasks:
    post:
      tags:
        - producer-controller
      operationId: create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UsertaskDto"
            examples:
              id_1:
                $ref: "#/components/examples/UsertaskDtoRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsertaskDto"
              examples:
                id_1:
                  $ref: "#/components/examples/UsertaskDtoResponse_200"
  /usertasks/{id}/completions:
    post:
      tags:
        - producer-controller
      operationId: complete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          examples:
            id_1:
              $ref: "#/components/examples/Id_1"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CompletionDto"
            examples:
              id_1:
                $ref: "#/components/examples/CompletionDtoRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompletionDto"
              examples:
                id_1:
                  $ref: "#/components/examples/CompletionDtoResponse_200"
components:
  schemas:
    CompletionMetadataDto:
      type: object
      properties:
        subscriptionName:
          type: string
        completionMessageRequired:
          type: boolean
        correlationData:
          type: object
          additionalProperties:
            type: string
    UsertaskDto:
      type: object
      properties:
        uuid:
          type: string
          readOnly: true
        usertaskType:
          type: string
        inputData:
          type: string
        customerId:
          type: integer
          format: int64
        createdBy:
          type: string
        completionMetadata:
          $ref: "#/components/schemas/CompletionMetadataDto"
    CompletionDto:
      type: object
      properties:
        outputData:
          type: string
  examples:
    UsertaskDtoRequest:
      value:
        usertaskType: ANY_USERTASK
        inputData: '{"test": "dummy"}'
        customerId: 34343253
        createdBy: Cristiano Dias
        completionMetadata:
          completionMessageRequired: true
          subscriptionName: customer-management-camunda-v1
          correlationData:
            myKey: dummy
            anotherKey: dummy
    UsertaskDtoResponse_200:
      value:
        uuid: 8d953bcb-9594-46bc-b35f-ac8c8c5dbf94
        usertaskType: ANY_USERTASK
        inputData: '{"test": "dummy"}'
        customerId: 34343253
        createdBy: Cristiano Dias
        completionMetadata:
          completionMessageRequired: true
          subscriptionName: customer-management-camunda-v1
          correlationData:
            myKey: dummy
            anotherKey: dummy
    Id_1:
      value: 8d953bcb-9594-46bc-b35f-ac8c8c5dbf94
    CompletionDtoRequest:
      value:
        outputData: '{"something": "dummy", "accepted": "true"}'
    CompletionDtoResponse_200:
      value:
        outputData: '{"something": "dummy", "accepted": "true"}'
